"""add time_slot_id to applications

Revision ID: 2d40e61dddd3
Revises: d2ac90652fbf
Create Date: 2025-05-12 11:47:36.933871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d40e61dddd3'
down_revision = 'd2ac90652fbf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('time_slot_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'applications', 'time_slots', ['time_slot_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'applications', type_='foreignkey')
    op.drop_column('applications', 'time_slot_id')
    # ### end Alembic commands ###