"""make time_slot_id not null in applications

Revision ID: c5c149af686e
Revises: 2d40e61dddd3
Create Date: 2025-05-12 11:52:57.434669

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5c149af686e'
down_revision = '2d40e61dddd3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('applications', 'time_slot_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('applications', 'time_slot_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###