"""add status to applications

Revision ID: ca961e6b0522
Revises: c5c149af686e
Create Date: 2025-05-12 13:01:48.070003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca961e6b0522'
down_revision = 'c5c149af686e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('status', sa.String(length=20), nullable=True))
    # После применения этой миграции необходимо вручную заполнить поле status для всех заявок,
    # затем сделать отдельную миграцию, чтобы сделать поле NOT NULL.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'status')
    # ### end Alembic commands ###