"""make city_id not null in time_slots

Revision ID: d2ac90652fbf
Revises: c88cc5b4af66
Create Date: 2025-05-12 10:41:25.327742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2ac90652fbf'
down_revision = 'c88cc5b4af66'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('time_slots', 'city_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('time_slots', 'city_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###